### ISSUE TITLE
can't download trading gym

### ISSUE THREAD

**Issue by Fishtang01** [thedimlebowski/Trading-Gym#13]
Hi, i am a novice python user, and i used pip3 install tgym and here is my error message:

Downloading tgym-0.1.13.tar.gz
Requirement already satisfied: matplotlib==2.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from tgym)
Requirement already satisfied: python-dateutil in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib==2.0.2->tgym)
Requirement already satisfied: six>=1.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib==2.0.2->tgym)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib==2.0.2->tgym)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib==2.0.2->tgym)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib==2.0.2->tgym)
Requirement already satisfied: numpy>=1.7.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from matplotlib==2.0.2->tgym)
Building wheels for collected packages: tgym
  Running setup.py bdist_wheel for tgym ... done
  Stored in directory: /Users/paul/Library/Caches/pip/wheels/09/e1/a4/6325c42ed40ac2b5bd72023483c4d23e710dcd7e4a8072a473
Successfully built tgym
Installing collected packages: tgym
Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted

is there something that I am not doing it right?  thanks for your help.

**Comment by Fishtang01** [comment]
after reading the previous 2 posts, I downloaded python 2.7 and use pip install instead of pip3 install and it worked.  no I just need to play around.

**Comment by jam-lock** [comment]
If you still wan't to try on python 3, you might run the command as an admin since the error was a 'PermissionError'

**Comment by Fishtang01** [comment]
Hi jam-lock it's laptop so i am the admin.

**Comment by Fishtang01** [comment]
does the code have python 3 support? thanks.

**Comment by jam-lock** [comment]
There's a pull request waiting for review [here](https://github.com/Prediction-Machines/Trading-Gym/pull/12).
You can download it from cove9988 repository https://github.com/cove9988/TradingGym
